export const carModels: { [brand: string]: string[] } = {
  Tesla: ['Model S', 'Model 3', 'Model X', 'Model Y', 'Roadster'],
  Ford: [
    'Mustang',
    'F-150',
    'Focus',
    'Escape',
    'Explorer',
    'Ranger',
    'Edge',
    'Fusion',
    'Expedition',
    'Bronco',
  ],
  Chevrolet: [
    'Camaro',
    'Silverado',
    'Equinox',
    'Malibu',
    'Tahoe',
    'Traverse',
    'Suburban',
    'Colorado',
    'Corvette',
    'Impala',
  ],
  Toyota: [
    'Corolla',
    'Camry',
    'RAV4',
    'Highlander',
    'Tacoma',
    'Sienna',
    'Prius',
    '4Runner',
    'Tundra',
    'Avalon',
  ],
  Honda: [
    'Accord',
    'Civic',
    'CR-V',
    'Pilot',
    'Odyssey',
    'Fit',
    'HR-V',
    'Ridgeline',
    'Passport',
    'Insight',
  ],
  BMW: [
    'X5',
    '3 Series',
    '5 Series',
    'X3',
    'X7',
    '7 Series',
    'X1',
    'X6',
    '4 Series',
    '2 Series',
  ],
  'Mercedes-Benz': [
    'E-Class',
    'C-Class',
    'GLC',
    'GLE',
    'S-Class',
    'GLS',
    'A-Class',
    'CLA',
    'GLA',
    'G-Class',
  ],
  Audi: ['A7', 'A4', 'Q5', 'Q7', 'A6', 'Q3', 'Q8', 'A3', 'A8', 'e-tron'],
  Volkswagen: [
    'Golf',
    'Jetta',
    'Tiguan',
    'Passat',
    'Atlas',
    'Arteon',
    'ID.4',
    'Touareg',
    'Atlas Cross Sport',
    'Beetle',
  ],
  Nissan: [
    'Altima',
    'Rogue',
    'Sentra',
    'Versa',
    'Murano',
    'Pathfinder',
    'Maxima',
    'Frontier',
    'Titan',
    'Armada',
  ],
};
export const carMarks: string[] = [
  'Tesla',
  'Ford',
  'Chevrolet',
  'Toyota',
  'Honda',
  'BMW',
  'Mercedes-Benz',
  'Audi',
  'Volkswagen',
  'Nissan',
];
